apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minicraft-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minicraft-server
    spec:
      containers:
      - env:
        - name: EULA
          value: "TRUE"
        image: openhack/minecraft-server
        resources:
          limits:
            memory: "2Gi"
        name: minicraft-server-container        
        ports:
        - containerPort: 25565