apiVersion: v1
kind: Service
metadata:
  name: minicraft-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    name: default
  - port: 25575
    name: rcon
  selector:
    app: minicraft-server