apiVersion: v1
kind: Secret
metadata:
  name: volume-azurefile-storage-secret
type: Opaque
data:
  azurestorageaccountname: [giovaniopenhackstr0]
  azurestorageaccountkey: [peZnC2rsCvMkGOpbmjitU8vFuV8yAOnyJAlroe1zcvLGv85TnLY9QKOe8QEAnMmKLxl4j3ajzTY2OoB/8330fQ==]