apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitor-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor-server
    spec:
      containers:
      - env:
          - name: MINECRAFT_ENDPOINT
            value: "13.70.120.193"                
        name: monitor-server-container
        image: minecraftacr.azurecr.io/minecraftlogreader      
      imagePullSecrets:
      - name: minecraftacrsecret